path: /home/temp/MyDir/Projects/Drons/HighRPD_parsed
batch_size: 32
name: mobilnet
finetune: lora
seed: 42
dataset:
  data_dir: tmp
trainer:
  max_epochs: 20
  lr: 0.001
  device: cpu
optimizer: adam
